### ISSUE TITLE
AttributeError: type object 'QDQBertConfig' has no attribute 'pretrained_config_archive_map'

### ISSUE THREAD

**Issue by DSLituiev** [facebookresearch/bio-lm#15]
I am trying to run an example from README.md and running into an error:

code:

```bash
TASK="BC5CDR-chem"
DATADIR="data/tasks/BC5CDR-chem.model=roberta-large.maxlen=512"
MODEL=roberta-large
MODEL_TYPE=roberta
python -m biolm.run_sequence_labelling \
    --data_dir ${DATADIR} \
    --model_type ${MODEL_TYPE} \
    --labels ${DATADIR}/labels.txt \
    --model_name_or_path ${MODEL} \
    --output_dir path/to/save/model/to \
    --max_seq_length  512 \
    --num_train_epochs 20 \
    --per_gpu_train_batch_size 8 \
    --save_steps 500 \
    --seed 10 \
    --gradient_accumulation_steps 4 \
    --do_train \
    --do_eval \
    --eval_all_checkpoints
```

Data is in the right place:
```sh
dir 'data/tasks/BC5CDR-chem.model=roberta-large.maxlen=512'
total 2.7M
-rw-r--r--. 1 dlituiev ichs 1.7M Apr  1 19:26 train.txt
-rw-r--r--. 1 dlituiev ichs 1.7M Apr  1 19:26 dev.txt
-rw-r--r--. 1 dlituiev ichs 1.7M Apr  1 19:27 test.txt
-rw-r--r--. 1 dlituiev ichs    6 Apr  1 19:27 labels.txt
```

Error:

```
Traceback (most recent call last):
  File "/wynton/protected/home/ichs/dlituiev/anaconda3/envs/torchnlp/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/wynton/protected/home/ichs/dlituiev/anaconda3/envs/torchnlp/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/wynton/protected/home/ichs/dlituiev/bio-lm/biolm/run_sequence_labelling.py", line 57, in <module>
    ALL_MODELS = sum((tuple(conf.pretrained_config_archive_map.keys()) for conf in MODEL_CONFIG_CLASSES), ())
  File "/wynton/protected/home/ichs/dlituiev/bio-lm/biolm/run_sequence_labelling.py", line 57, in <genexpr>
    ALL_MODELS = sum((tuple(conf.pretrained_config_archive_map.keys()) for conf in MODEL_CONFIG_CLASSES), ())
AttributeError: type object 'QDQBertConfig' has no attribute 'pretrained_config_archive_map'
```

**Comment by DSLituiev** [comment]
I had to remove the line that assigns `ALL_MODELS` (57) and the line that calls it. Now it works.
